In [ ]:
import cv2
import tensorflow as tf
from tensorflow import keras
from PIL import Image

In [ ]:
print(tf.__version__)

In [2]:
import matplotlib.pyplot as plt

In [3]:
image = r'test_photo.jpg'
face_cascade = "haarcascade_frontalface_default.xml"

In [4]:
image_bgr = cv2.imread(image)
image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

In [5]:
face_classifier = cv2.CascadeClassifier(face_cascade)
faces = face_classifier.detectMultiScale(image_bw)

In [6]:
print(f'There are {len(faces)} faces found.')

There are 1 faces found.


In [7]:
for face in faces:
    x, y, w, h = face
    cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)

In [8]:
cv2.imshow("Faces found", image_bgr)
cv2.waitKey(0) 

-1

In [9]:
webcam = cv2.VideoCapture(0)
webcam

<VideoCapture 0000023527A7C950>

In [10]:
success, image_bgr = webcam.read()
#print(success, image_bgr)

In [11]:
face_cascade = "haarcascade_frontalface_default.xml"

In [12]:
# while True:
 
#     success, image_bgr = webcam.read()
#     image_org = image_bgr.copy()
#     image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

#     face_classifier = cv2.CascadeClassifier(face_cascade)
#     faces = face_classifier.detectMultiScale(image_bw)

#     print(f'There are {len(faces)} faces found.')

#     for face in faces:
#         x, y, w, h = face
#         cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
#         image_org[y:y+h,x:x+w]
        
#     cv2.imshow("Faces found", image_bgr)
#     cv2.waitKey(1) 

In [13]:
# count = 9999
# while True:
 
#     success, image_bgr = webcam.read()
#     image_org = image_bgr.copy()
#     image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)

#     face_classifier = cv2.CascadeClassifier(face_cascade)
#     faces = face_classifier.detectMultiScale(image_bw)

#     print(f'There are {len(faces)} faces found.')

#     for face in faces:
#         x, y, w, h = face
#         cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
#         cv2.imwrite(f'wearmask/wearmask_{count}.jpg',image_org[y:y+h,x:x+w])
#         count += 1

#     cv2.imshow("Faces found", image_bgr)
#     cv2.waitKey(1) 

In [14]:
import tensorflow.keras
from PIL import Image
from PIL import ImageOps
import numpy as np

In [15]:
np.set_printoptions(suppress=True)

In [16]:
model = tensorflow.keras.models.load_model('keras_model.h5')

In [17]:
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

In [18]:
import os
from PIL import Image

curDir = os.getcwd()
fileName = "test_photo.jpg"
fn = curDir + "\\" + fileName
print(fn)

from os import listdir
from os.path import isfile, join

onlyfiles = [f for f in listdir(curDir) if isfile(join(curDir, f))]
print(onlyfiles)

image = Image.open(fn)
# image.show()

C:\Users\Admin\Senior Project\test_photo1.jpg
['a.jpg', 'haarcascade_frontalface_default.xml', 'keras_model.h5', 'labels.txt', 'mask detect.ipynb', 'test2_1080.jpg', 'test_photo.jpg', 'test_photo1.jpg', 'test_photo1080.jpg', 'test_photo360.jpg', 'test_photo720.jpg']


In [19]:
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

In [20]:
image_array = np.asarray(image)

In [21]:
image.show()

In [22]:
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

In [34]:
prediction = model.predict(data)
print(prediction)

[[0.8566341  0.14336589]]


In [35]:
webcam = cv2.VideoCapture(0)
success, image_bgr = webcam.read()

In [36]:
image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)

In [37]:
cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])

In [45]:
face_classifier = cv2.CascadeClassifier(face_cascade)
np.set_printoptions(suppress=True)
model = tensorflow.keras.models.load_model('keras_model.h5')
size = (224, 224)

In [39]:
# while True:
#     success, image_bgr = webcam.read()
#     image_org = image_bgr.copy()
#     image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
#     image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)
#     faces = face_classifier.detectMultiScale(image_bw)
#     for face in faces:
#         x, y, w, h = face
#         cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])
#         data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
#         image = cface_rgb
#         image = ImageOps.fit(image, size, Image.ANTIALIAS)
#         image_array = np.asarray(image)
#         normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
#         data[0] = normalized_image_array
#         prediction = model.predict(data)
#         print(prediction)
#         cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
#     cv2.imshow("Mask Detection", image_bgr)
#     cv2.waitKey(1) 

In [40]:
count = 0
while True:
    success, image_bgr = webcam.read()
    image_org = image_bgr.copy()
    image_bw = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
    image_rgb = cv2.cvtColor(image_bgr,cv2.COLOR_BGR2RGB)
    faces = face_classifier.detectMultiScale(image_bw)
    for face in faces:
        x, y, w, h = face
        cface_rgb = Image.fromarray(image_rgb[y:y+h,x:x+w])
        data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
        image = cface_rgb
        image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image_array = np.asarray(image)
        normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
        data[0] = normalized_image_array
        prediction = model.predict(data)
        print(prediction)
        if prediction[0][1] < prediction[0][0]:
            cv2.putText(image_bgr,'Non-Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,0,255),2)
            cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0,0,255), 2)
            cv2.imwrite(f'nomask/nomask_{count}.jpg',image_org[y:y+h,x:x+w])
            count += 1
            
        else:
            cv2.putText(image_bgr,'Masked',(x,y-7),cv2.FONT_HERSHEY_SIMPLEX,0.5,(0,255,0),2)
            cv2.rectangle(image_bgr, (x, y), (x+w, y+h), (0, 255, 0), 2)
            cv2.imwrite(f'wearmask/wearmask_{count}.jpg',image_org[y:y+h,x:x+w])
            count += 1
            
    cv2.imshow("Mask Detection", image_bgr)
    cv2.waitKey(1) 

[[0.999961   0.00003902]]
[[0.99990976 0.00009021]]
[[0.999907   0.00009297]]
[[0.9999573  0.00004264]]
[[0.9999331  0.00006682]]
[[0.9999335  0.00006657]]
[[0.9999411  0.00005884]]
[[0.9999193  0.00008074]]
[[0.99995494 0.00004508]]
[[0.9956599  0.00434012]]
[[0.999959   0.00004096]]
[[0.9999361  0.00006389]]
[[0.99993396 0.00006603]]
[[0.99991345 0.00008654]]
[[0.9998933  0.00010673]]
[[0.9999372  0.00006278]]
[[0.99995077 0.0000492 ]]
[[0.99996316 0.00003688]]
[[0.9999366  0.00006342]]
[[0.9999449 0.0000551]]
[[0.9999578  0.00004224]]
[[0.99990225 0.00009774]]
[[0.9999026  0.00009744]]
[[0.9999596  0.00004047]]
[[0.99997365 0.00002634]]
[[0.9999219  0.00007806]]
[[0.99989605 0.00010389]]
[[0.9998572  0.00014284]]
[[0.99987936 0.00012068]]
[[0.9999492  0.00005079]]
[[0.99993277 0.00006728]]
[[0.99992776 0.00007227]]
[[0.99986374 0.00013626]]
[[0.9999058  0.00009414]]
[[0.999954   0.00004605]]
[[0.99993527 0.00006473]]
[[0.99991894 0.00008111]]
[[0.9999093  0.00009067]]
[[0.9998995  0

KeyboardInterrupt: 